name: deploy-docs

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up the environment
        uses: ./.github/actions/setup-pdm-env

      - name: Deploy documentation
        run: pdm run mkdocs gh-deploy --force
